##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - cppcheck
    - curl

variables:
  - 'CHECKIDS="warning,style,performance,portability,information,missingInclude"'

build_scripts:
  - ./docppcheck.sh
  - cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=libhandy_cppcheck-htmlreport --source-encoding="iso8859-1" &> /dev/null
  - tar -zcf libhandy_cppcheck-htmlreport.tar.gz libhandy_cppcheck-htmlreport
  - curl -F file=@libhandy_cppcheck-htmlreport.tar.gz -F expires=6m -F no_index=true https://api.anonymousfiles.io/ && echo
